load("//tools/bzl:plugin.bzl", "gerrit_plugin")

gerrit_plugin(
    name = "gitblit",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**/*"]),
    manifest_entries = [
        "Gerrit-PluginName: gitblit",
        "Gerrit-Module: com.googlesource.gerrit.plugins.gitblit.GitBlitModule",
        "Gerrit-HttpModule: com.googlesource.gerrit.plugins.gitblit.GitBlitServletModule",
        "Gerrit-InitStep: com.googlesource.gerrit.plugins.gitblit.GitBlitInitStep",
        "Gerrit-ReloadMode: restart",
    ],
    deps = [
        "@commons-codec//jar:neverlink",
        "@commons-io//jar",
        "@commons-net//jar:neverlink",
        "@confluence-core//jar",
        "@force-partner-api//jar",
        "@freemarker//jar",
        "@gitblit-jar//jar",
        "@groovy//jar",
        "@httpcore//jar:neverlink",
        "@ivy//jar",
        "@jdom//jar",
        "@libpam4j//jar",
        "@lucene-core//jar:neverlink",
        "@lucene-highlighter//jar",
        "@lucene-memory//jar",
        "@mail//jar",
        "@markdownpapers//jar",
        "@mediawiki-core//jar",
        "@pf4j//jar",
        "@rome//jar",
        "@textile-core//jar",
        "@tika//jar",
        "@tracwiki-core//jar",
        "@twiki-core//jar",
        "@unboundid//jar",
        "@waffle-jna//jar",
        "@wicket//jar",
        "@wicket-extensions//jar",
        "@wikitext-core//jar",
    ],
)
