package(default_visibility = ["//visibility:public"])

java_library(
    name = "pf4j",
    exports = ["@pf4j//jar"],
)

java_library(
    name = "gitblit-jar",
    exports = ["@gitblit_jar//jar"],
)

java_library(
    name = "wicket",
    exports = ["@wicket//jar"],
)

java_library(
    name = "wicket-auth-roles",
    exports = ["@wicket_auth_roles//jar"],
)

java_library(
    name = "wicket-extensions",
    exports = ["@wicket_extensions//jar"],
)

java_library(
    name = "groovy",
    exports = ["@groovy//jar"],
)

java_library(
    name = "jdom",
    exports = ["@jdom//jar"],
)

java_library(
    name = "lucene-core",
    exports = ["@lucene_core//jar"],
)

java_library(
    name = "lucene-highlighter",
    exports = ["@lucene_highlighter//jar"],
)

java_library(
    name = "lucene-memory",
    exports = ["@lucene_memory//jar"],
)

java_library(
    name = "markdownpapers",
    exports = ["@markdownpapers//jar"],
)

java_library(
    name = "rome",
    exports = ["@rome//jar"],
)

java_library(
    name = "unboundid",
    exports = ["@unboundid//jar"],
)

java_library(
    name = "jsoup",
    exports = ["@jsoup//jar"],
)

java_library(
    name = "tika",
    exports = ["@tika//jar"],
)

java_library(
    name = "wikitext-core",
    exports = ["@wikitext_core//jar"],
)

java_library(
    name = "twiki-core",
    exports = ["@twiki_core//jar"],
)

java_library(
    name = "textile-core",
    exports = ["@textile_core//jar"],
)

java_library(
    name = "tracwiki-core",
    exports = ["@tracwiki_core//jar"],
)

java_library(
    name = "mediawiki-core",
    exports = ["@mediawiki_core//jar"],
)

java_library(
    name = "confluence-core",
    exports = ["@confluence_core//jar"],
)

java_library(
    name = "ivy",
    exports = ["@ivy//jar"],
)

java_library(
    name = "force-partner-api",
    exports = ["@force_partner_api//jar"],
)

java_library(
    name = "freemarker",
    exports = ["@freemarker//jar"],
)

java_library(
    name = "waffle-jna",
    exports = ["@waffle_jna//jar"],
)

java_library(
    name = "libpam4j",
    exports = ["@libpam4j//jar"],
)
