package(default_visibility = ["//visibility:public"])

java_library(
    name = "pf4j",
    exports = ["@pf4j//jar"],
)

java_library(
    name = "gitblit-jar",
    exports = ["@gitblit-jar//jar"],
)

java_library(
    name = "wicket",
    exports = ["@wicket//jar"],
)

java_library(
    name = "wicket-auth-roles",
    exports = ["@wicket-auth-roles//jar"],
)

java_library(
    name = "wicket-extensions",
    exports = ["@wicket-extensions//jar"],
)

java_library(
    name = "javax-mail",
    exports = ["@javax-mail//jar"],
)

java_library(
    name = "groovy",
    exports = ["@groovy//jar"],
)

java_library(
    name = "jdom",
    exports = ["@jdom//jar"],
)

java_library(
    name = "lucene-core",
    exports = ["@lucene-core//jar"],
)

java_library(
    name = "lucene-highlighter",
    exports = ["@lucene-highlighter//jar"],
)

java_library(
    name = "lucene-memory",
    exports = ["@lucene-memory//jar"],
)

java_library(
    name = "markdownpapers",
    exports = ["@markdownpapers//jar"],
)

java_library(
    name = "rome",
    exports = ["@rome//jar"],
)

java_library(
    name = "unboundid",
    exports = ["@unboundid//jar"],
)

java_library(
    name = "jsoup",
    exports = ["@jsoup//jar"],
)

java_library(
    name = "tika",
    exports = ["@tika//jar"],
)

java_library(
    name = "wikitext-core",
    exports = ["@wikitext-core//jar"],
)

java_library(
    name = "twiki-core",
    exports = ["@twiki-core//jar"],
)

java_library(
    name = "textile-core",
    exports = ["@textile-core//jar"],
)

java_library(
    name = "tracwiki-core",
    exports = ["@tracwiki-core//jar"],
)

java_library(
    name = "mediawiki-core",
    exports = ["@mediawiki-core//jar"],
)

java_library(
    name = "confluence-core",
    exports = ["@confluence-core//jar"],
)

java_library(
    name = "ivy",
    exports = ["@ivy//jar"],
)

java_library(
    name = "force-partner-api",
    exports = ["@force-partner-api//jar"],
)

java_library(
    name = "freemarker",
    exports = ["@freemarker//jar"],
)

java_library(
    name = "waffle-jna",
    exports = ["@waffle-jna//jar"],
)

java_library(
    name = "libpam4j",
    exports = ["@libpam4j//jar"],
)
